# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0004_auto_20170322_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.TextField(),
        ),
    ]
