# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0005_auto_20170426_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
