# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='colour',
            field=models.CharField(default='#FFFFFF', max_length=8),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTodolist.TaskList'),
        ),
    ]
