# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0007_auto_20170503_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appTodolist.TaskList'),
        ),
    ]
