# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0008_auto_20170503_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BigIntegerField(null=True),
        ),
    ]
